services:
    api:
        container_name: api
        build:
            context: ./
            dockerfile: ./api/Dockerfile.compose-dev
        image: 4rgc/trellzo-backend-api:dev
        volumes:
            - ./api:/app
        ports:
            - 3000:8080

    mongodb:
        container_name: mongodb
        build:
            context: ./
            dockerfile: ./mongo/Dockerfile.compose-dev
        image: 4rgc/trellzo-backend-mongo:dev
        ports:
            - 27017-27019:27017-27019
        environment:
            MONGO_INITDB_DATABASE: 'trellzo'

    mongo-seed:
        container_name: mongodb-seed
        image: stefanwalther/mongo-seed
        environment:
            - MONGODB_HOST=mongodb
            - MONGODB_PORT=27017
        volumes:
            - ./mongo/db-seed:/data
        depends_on:
            - mongodb
        command: [
                'mongoimport --host mongodb --port 27017 --db trellzo -c users
                --mode upsert --type json --file /data/user.json --jsonArray',
            ]
