version: "3.9"

services:
    api:
        container_name: api
        build:
            context: ./
            dockerfile: ./Dockerfile.api-dev
        image: 4rgc/trellzo-backend-api:dev
        volumes:
            - ./api:/app
            - ./scripts:/scripts
            - node_modules:/app/node_modules
        ports:
            - 3000:8080
        networks:
            def:
                ipv4_address: 192.168.2.3
        restart: on-failure
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080"]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s

    mongodb:
        container_name: mongodb
        build:
            context: ./
            dockerfile: ./mongo/Dockerfile.dev
        image: 4rgc/trellzo-backend-mongo:dev
        ports:
            - 27017-27019:27017-27019
        environment:
            MONGO_INITDB_DATABASE: 'trellzo'
        volumes:
            - mongo_db_data:/data/db
            - mongo_db_config:/data/configdb
        networks:
            def:
                ipv4_address: 192.168.2.2

    mongo-seed:
        container_name: mongodb-seed
        image: stefanwalther/mongo-seed
        environment:
            - MONGODB_HOST=mongodb
            - MONGODB_PORT=27017
        volumes:
            - ./mongo/db-seed:/data
        depends_on:
            - mongodb
        networks:
            def:
                ipv4_address: 192.168.2.4
        command: [
                'mongoimport --host mongodb --port 27017 --db trellzo -c users
                --mode upsert --type json --file /data/user.json --jsonArray',
                '&&',
                'mongoimport --host mongodb --port 27017 --db trellzo -c boards
                --mode upsert --type json --file /data/board.json --jsonArray',
                '&&',
                'mongoimport --host mongodb --port 27017 --db trellzo -c notes
                --mode upsert --type json --file /data/note.json --jsonArray',
            ]

volumes:
    node_modules:
    mongo_db_data:
    mongo_db_config:

networks:
    def:
        ipam:
            driver: default
            config:
                - subnet: "192.168.2.0/24"
