services:
    remote-seed:
        image: remote-seed
        volumes:
            - ./mongo/db-seed/prod:/mongo_data
        build:
            context: ./mongo/db-seed
            dockerfile: Dockerfile.compose-dev
        environment:
            - MONGODB_HOST
            - MONGODB_USER
            - MONGODB_PASSWORD
