name: Continuous Integration
on:
    push:
        branches: '*'
    pull_request:
        branches: '*'
jobs:
    test:
        environment: Continuous Integration
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - name: Install nodejs packages
              run: |
                  npm install
                  npm --prefix ./api install ./api

            - name: Create env file
              env:
                  BCRYPT_SALT_ROUNDS: ${{ secrets.BCRYPT_SALT_ROUNDS }}
                  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
                  REFRESH_SECRET_KEY: ${{ secrets.REFRESH_SECRET_KEY }}
              run: |
                  touch api/.env
                  echo BCRYPT_SALT_ROUNDS="$BCRYPT_SALT_ROUNDS" >> api/.env
                  echo JWT_SECRET_KEY="$JWT_SECRET_KEY" >> api/.env
                  echo REFRESH_SECRET_KEY="$REFRESH_SECRET_KEY" >> api/.env
                  cat api/.env
            - name: Build the stack
              run: docker-compose up -d
            - name: Inspect the network
              run: |
                  docker network ls
                  docker network inspect trellzo-backend_def
            - name: API smoke test
              run: |
                  docker logs api --timestamps
                  docker stats --no-stream
                  docker container ls -a
                  docker exec api ps -l | grep node
                  docker exec api ping 192.168.2.3 -c 8
                  docker run --network trellzo-backend_def appropriate/curl --retry 10 --retry-connrefused http://192.168.2.3:8080
            - name: API Test
              uses: matt-ball/newman-action@master
              with:
                  collection: api/Trellzo.postman_collection.json
                  iterationData: api/postman-test-data.json
            - name: Final smoke test
              if: always()
              run: |
                  docker logs api --timestamps
                  docker stats --no-stream
                  docker container ls -a
                  docker exec api ps -l | grep node
                  docker exec api ping 192.168.2.3 -c 8
