name: Continuous Integration
on:
    push:
        branches: '*'
    pull_request:
        branches: '*'
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Create env file
              env:
                  BCRYPT_SALT_ROUNDS: ${{ secrets.BCRYPT_SALT_ROUNDS }}
                  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
                  REFRESH_SECRET_KEY: ${{ secrets.REFRESH_SECRET_KEY }}
              run: |
                  touch api/.env
                  echo BCRYPT_SALT_ROUNDS=$BCRYPT_SALT_ROUNDS >> api/.env
                  echo JWT_SECRET_KEY=$JWT_SECRET_KEY >> api/.env
                  echo REFRESH_SECRET_KEY=$REFRESH_SECRET_KEY >> api/.env
                  cat api/.env
            - name: Build the stack
              run: docker-compose up -d
            - name: Check containers in network
              run: |
                  docker network ls
                  docker network inspect trellzo-backend_default
            - name: API smoke test
              run: docker run --network trellzo-backend_default appropriate/curl --retry 10 --retry-connrefused http://172.18.0.3:8080
            - name: API Test
              uses: matt-ball/newman-action@master
              with:
                  collection: api/Trellzo.postman_collection.json
                  iterationData: api/postman-test-data.json
